name: ci

on:
  push:
    branches:
      - main # with #262 - ${{{ github.default_branch }}}
  pull_request:
    branches:
      - '**'

jobs:
  build:
    # Job name is Greeting
    name: build
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: yarn install --frozen-lockfile
      - name: Run linter
        run: yarn run lint
      - name: Build
        run: yarn run build
      - uses: tj-actions/verify-changed-files@v9
        id: verify-changed-files
        with:
          files: |
             packages/snap/snap.manifest.json

      - name: Check if snap manifest updated
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          echo "Snap manifest not updated: ${{ steps.verify-changed-files.outputs.changed_files }}"
          exit 1
